name: MATCH

model:
  hidden_size: 100
  n_layers: 3
  n_probes: 8
  n_aheads: 2
  intermediate_size: 50
  dropout: 0.1
  src_max_len: 125

train:
  batch_size: 128
  nb_epoch: 5
  swa_warmup: 4

valid:
  batch_size: 128

predict:
  batch_size: 128

path: MeSH/models
